# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
np.version.version

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [6]:
# Method 1
a = np.random.random((2,3,5))
print(a)

[[[0.89493274 0.19103379 0.15873073 0.94055466 0.67861742]
  [0.24743413 0.22628309 0.41619915 0.13595582 0.89178697]
  [0.72451045 0.6022443  0.46769166 0.0900906  0.51655288]]

 [[0.20207892 0.62071056 0.65449417 0.43210077 0.30417176]
  [0.02977667 0.80117477 0.30913612 0.86548501 0.6220768 ]
  [0.4898783  0.26674006 0.57789156 0.07363315 0.13014953]]]


In [12]:
# Method 2
a = np.arange(30).reshape(2,3,5)
print(a)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [15]:
# Method 3
a = np.empty((2,3,5))
print(a)

[[[0.00e+000 4.94e-324 9.88e-324 1.48e-323 1.98e-323]
  [2.47e-323 2.96e-323 3.46e-323 3.95e-323 4.45e-323]
  [4.94e-323 5.43e-323 5.93e-323 6.42e-323 6.92e-323]]

 [[7.41e-323 7.91e-323 8.40e-323 8.89e-323 9.39e-323]
  [9.88e-323 1.04e-322 1.09e-322 1.14e-322 1.19e-322]
  [1.24e-322 1.28e-322 1.33e-322 1.38e-322 1.43e-322]]]


#### 4. Print *a*.


In [16]:
# your code here
a = np.random.random((2,3,5))
print(a)

[[[0.06675083 0.75389386 0.47046435 0.11736118 0.69168738]
  [0.39806391 0.17722    0.41561356 0.66307519 0.5126453 ]
  [0.81204573 0.58363554 0.58052098 0.39155931 0.48538394]]

 [[0.47717809 0.10120235 0.01337163 0.81447359 0.79772864]
  [0.8100521  0.44160023 0.87364738 0.1635281  0.80628966]
  [0.57341772 0.64479065 0.37302195 0.95187275 0.09680689]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [18]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [19]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [23]:
# your code here
if a.size == b.size:
    print('yeah')
else:
    print('nope')

yeah


#### 8. Are you able to add *a* and *b*? Why or why not?


In [27]:
# your answer here
#its not possible as they dont have the same shape, in order to sum they need to have some conditions
np.add(a,b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [30]:
# your code here
c = b.reshape(2,3,5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [32]:
# your code/answer here
#they have the same shape now so the sum can work
d = np.add(a,c)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [33]:
# your code/answer here
print(a)
print(d)
# d has the same values as a + 1 because c is a reshaped version of, which was a matrix of only 1 values

[[[0.06675083 0.75389386 0.47046435 0.11736118 0.69168738]
  [0.39806391 0.17722    0.41561356 0.66307519 0.5126453 ]
  [0.81204573 0.58363554 0.58052098 0.39155931 0.48538394]]

 [[0.47717809 0.10120235 0.01337163 0.81447359 0.79772864]
  [0.8100521  0.44160023 0.87364738 0.1635281  0.80628966]
  [0.57341772 0.64479065 0.37302195 0.95187275 0.09680689]]]
[[[1.06675083 1.75389386 1.47046435 1.11736118 1.69168738]
  [1.39806391 1.17722    1.41561356 1.66307519 1.5126453 ]
  [1.81204573 1.58363554 1.58052098 1.39155931 1.48538394]]

 [[1.47717809 1.10120235 1.01337163 1.81447359 1.79772864]
  [1.8100521  1.44160023 1.87364738 1.1635281  1.80628966]
  [1.57341772 1.64479065 1.37302195 1.95187275 1.09680689]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [34]:
# your code here
e = np.multiply(a,c)

#### 13. Does *e* equal to *a*? Why or why not?


In [35]:
# your code/answer here
# it is equal since multiplication by 1 produces the same result
print(a)

[[[0.06675083 0.75389386 0.47046435 0.11736118 0.69168738]
  [0.39806391 0.17722    0.41561356 0.66307519 0.5126453 ]
  [0.81204573 0.58363554 0.58052098 0.39155931 0.48538394]]

 [[0.47717809 0.10120235 0.01337163 0.81447359 0.79772864]
  [0.8100521  0.44160023 0.87364738 0.1635281  0.80628966]
  [0.57341772 0.64479065 0.37302195 0.95187275 0.09680689]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [47]:
# your code here
d_max = np.amax(d)
d_min = np.amin(d)
d_mean = np.mean(d)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [91]:
# your code here
f = np.empty((2,3,5))
f

array([[[-2.68156159e+154, -2.68156159e+154,  8.89318163e-323,
          0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
          0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
          0.00000000e+000,  0.00000000e+000]],

       [[ 7.68724739e+170, -2.68156159e+154, -2.68156159e+154,
          8.37174974e-144,  6.64573734e-066],
        [ 9.77381441e+165,  1.82586529e+184,  5.24341212e+174,
          5.28555805e+180,  4.96924456e-091],
        [ 6.42765986e-067,  1.30473617e-076,  4.29600106e-096,
          9.08366791e+223,  5.81186265e+294]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [92]:
# your code here
i = 0
while i < len(d):
    j = 0
    while j < len(d[i]):
        k = 0
        while k < len(d[i][j]):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                f[i][j][k] = 25
            if d[i][j][k] > d_mean and d[i][j][k] < d_max:
                f[i][j][k] = 75
            if d[i][j][k] == d_mean:
                f[i][j][k] = 50
            if d[i][j][k] == d_min:
                f[i][j][k] = 0
            if d[i][j][k] == d_max:
                f[i][j][k] = 100
            k +=1
        j += 1
    i += 1

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [93]:
# your code here
print(d)
print(f)

[[[1.06675083 1.75389386 1.47046435 1.11736118 1.69168738]
  [1.39806391 1.17722    1.41561356 1.66307519 1.5126453 ]
  [1.81204573 1.58363554 1.58052098 1.39155931 1.48538394]]

 [[1.47717809 1.10120235 1.01337163 1.81447359 1.79772864]
  [1.8100521  1.44160023 1.87364738 1.1635281  1.80628966]
  [1.57341772 1.64479065 1.37302195 1.95187275 1.09680689]]]
[[[ 25.  75.  25.  25.  75.]
  [ 25.  25.  25.  75.  75.]
  [ 75.  75.  75.  25.  25.]]

 [[ 25.  25.   0.  75.  75.]
  [ 75.  25.  75.  25.  75.]
  [ 75.  75.  25. 100.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [94]:
# your code here
f = np.array(f, dtype = 'object')
f[f == 0] = 'a'
f[f == 25] = 'b'
f[f == 50] = 'c'
f[f == 75] = 'd'
f[f == 100] = 'e'
f

array([[['b', 'd', 'b', 'b', 'd'],
        ['b', 'b', 'b', 'd', 'd'],
        ['d', 'd', 'd', 'b', 'b']],

       [['b', 'b', 'a', 'd', 'd'],
        ['d', 'b', 'd', 'b', 'd'],
        ['d', 'd', 'b', 'e', 'b']]], dtype=object)