# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here

import sys
# print(sys.path)
# Adding a path so that it finds the package for numpy
sys.path.append('/usr/local/lib/python3.7/site-packages')
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here

np.version.version

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1

a = np.random.random((2,3,5))



In [4]:
# Method 2

a = np.random.uniform(0,100,(2,3,5))




In [5]:
# Method 3

a = np.random.randint(100, size=(2,3,5))



#### 4. Print *a*.


In [6]:
# your code here

print(a)

[[[44 66  6  5 86]
  [71 94 63 38  3]
  [95 62 58 98 85]]

 [[83 79 59 85 79]
  [66 76 61 69 55]
  [17 77 79 76 45]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here

b = np.random.uniform(1,1,(5,2,3))



#### 6. Print *b*.


In [8]:
# your code here

print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here

def check_size(a, b):
    a_size = a.shape
    b_size = b.shape
    if a_size == b_size:
        
        return print("Same size")
    
    else:
        
        return print("Not the same size")
        
check_size(a, b)     

Not the same size


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here

"""No, You need two matrix of the same size"""


'No, You need two matrix of the same size'

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here

c = np.transpose(b, (1, 2, 0))

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here

d = a + c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here

print(a)
print(d)

"""every element of d is +1 vs a since b had all elements = 1 and d = a+transpopsed b"""

[[[44 66  6  5 86]
  [71 94 63 38  3]
  [95 62 58 98 85]]

 [[83 79 59 85 79]
  [66 76 61 69 55]
  [17 77 79 76 45]]]
[[[45. 67.  7.  6. 87.]
  [72. 95. 64. 39.  4.]
  [96. 63. 59. 99. 86.]]

 [[84. 80. 60. 86. 80.]
  [67. 77. 62. 70. 56.]
  [18. 78. 80. 77. 46.]]]


'every element of d is +1 vs a since b had all elements = 1 and d = a+transpopsed b'



#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here

e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here

"""Yes because b = 1"""

'Yes because b = 1'

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here

f = np.empty([2, 3, 5])

print(f)

[[[45. 67.  7.  6. 87.]
  [72. 95. 64. 39.  4.]
  [96. 63. 59. 99. 86.]]

 [[84. 80. 60. 86. 80.]
  [67. 77. 62. 70. 56.]
  [18. 78. 80. 77. 46.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
# your code here


for x in range(0, d.shape[0]):
    for y in range(0, d.shape[1]):
        for z in range(0, d.shape[2]):
            if d[x, y, z] == d_min:
                f[x, y, z] = 0
            elif d[x, y, z] > d_min and d[x, y, z] < d_mean:
                f[x, y, z] = 25
            elif d[x, y, z] == d_mean:
                f[x, y, z] = 50
            elif d[x, y, z] > d_mean and d[x, y, z] < d_max:
                f[x, y, z] = 75
            else:
                f[x, y, z] = 100




#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [19]:
# your code here

print(d)

print(d_min)
print(d_mean)
print(d_max)

print(f)

[[[45. 67.  7.  6. 87.]
  [72. 95. 64. 39.  4.]
  [96. 63. 59. 99. 86.]]

 [[84. 80. 60. 86. 80.]
  [67. 77. 62. 70. 56.]
  [18. 78. 80. 77. 46.]]]
4.0
63.666666666666664
99.0
[[[ 25.  75.  25.  25.  75.]
  [ 75.  75.  75.  25.   0.]
  [ 75.  25.  25. 100.  75.]]

 [[ 75.  75.  25.  75.  75.]
  [ 75.  75.  25.  75.  25.]
  [ 25.  75.  75.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [20]:
# your code here